---
efiBootLoader: "grub"
grubInstall: "grub-install"
grubMkconfig: "/usr/bin/true"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
installHybridGRUB: false
