---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "gdm.service"
    action: "enable"
    mandatory: true
  - name: "sshd.service"
    action: "disable"
  - name: "cloud-init-local.service"
    action: "disable"
  - name: "cloud-init-network.service"
    action: "disable"
  - name: "cloud-init-main.service"
    action: "disable"
  - name: "cloud-config.service"
    action: "disable"
  - name: "cloud-final.service"
    action: "disable"
