---
dontChroot: false
timeout: 300
verbose: true
script:
  - command: "bash /usr/local/lib/oxsystemsos/verify-boot-artifacts"
    timeout: 300
    verbose: true
i18n:
  name: "Verify installed boot artifacts"
