---
dontChroot: false
timeout: 300
verbose: true
script:
  - command: "bash /usr/local/lib/oxsystemsos/write-grub-config"
    timeout: 300
    verbose: true
i18n:
  name: "Write static GRUB configuration"
